sharingcars/common/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from common.views import (UserCreateView, UserProfileView, UserUpdateView, MessageCreateView, MessageDetailsView,
                          FolderDetailsView, ajax_delete_message, ajax_hide_message, ReplyMessageView,
                          CommentCreateView)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='common/index.html'),
        name='index'),
    url(r'^login/?$', 'django.contrib.auth.views.login',
        {'template_name': 'common/registration/login.html'}, name="login"),
    url(r'^logout/?$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),
    url(r'^user/register$', UserCreateView.as_view(), name='create-user'),
    url(r'^user/update/(?P<username>.*)/$', UserUpdateView.as_view(), name='user-update'),
    url(r'^user/(?P<username>.*)/$', UserProfileView.as_view(), name='user-profile'),
    url(r'^messages/send/$', MessageCreateView.as_view(), name='messages-send'),
    url(r'^messages/delete/(?P<pk>[-\d]+)$', ajax_delete_message, name='messages-delete'),
    url(r'^messages/reply/(?P<pk>[-\d]+)$', ReplyMessageView.as_view(), name='messages-reply'),
    url(r'^messages/hide/(?P<pk>[-\d]+)/(?P<type>[-\w]+)$', ajax_hide_message, name='messages-mark-not-see'),
    url(r'^messages/(?P<type>[-\w]+)/$', FolderDetailsView.as_view(), name='messages-details'),
    url(r'^messages/(?P<type>[-\w]+)/(?P<pk>[-\w]+)$', MessageDetailsView.as_view(), name='messages-see'),
    url(r'^comment/(?P<username>.*)/$', CommentCreateView.as_view(), name='comment-create'),


]

sharingcars/sharingcars/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('common.urls')),
    url(r'^announcements/', include('announcements.urls')),
    url(r'^routes/', include('routes.urls')),
]

sharingcars/announcements/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from common.models import APPLY_STATUS
from common.models import User


class Announcement(models.Model):
    KINDS = (
        ('offer', 'Oferta'),
        ('demand', 'Demanda'),
    )
    origin = models.CharField(max_length=256, blank=False)
    destination = models.CharField(max_length=256, blank=False)
    description = models.TextField(blank=False)
    kind = models.CharField(max_length=64, choices=KINDS, blank=False)
    visibility = models.BooleanField(default=False)
    seating = models.IntegerField(validators=[MinValueValidator(0)],
                                  blank=False)
    unitPrice = models.DecimalField(max_digits=5, decimal_places=2,
                                    validators=[MinValueValidator(0)],
                                    blank=False)
    date = models.DateTimeField(blank=False)
    creationMoment = models.DateTimeField(auto_now=False, auto_now_add=True)

    user = models.ForeignKey(User)

    def __unicode__(self):
        return '%s - %s - %s' % (self.origin, self.destination, self.date)

    def get_rating(self):
        rating = 0
        if self.commentannouncement_set.all():
            rating = round(self.commentannouncement_set.all().aggregate(models.Sum('rating')).get('rating__sum', 0)/float(self.commentannouncement_set.all().count()), 1)
        return rating

    def check_applies(self):
        if self.seating == self.applyannouncement_set.filter(state='approach').count():
            self.applyannouncement_set.filter(state='waiting').update(state='rejected')

    def get_seats_free(self):
        return self.seating - self.applyannouncement_set.filter(state='approach').count()


class ApplyAnnouncement(models.Model):
    creationDate = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=False, max_length=395)
    state = models.CharField(max_length=64, choices=APPLY_STATUS, default="waiting")

    announcement = models.ForeignKey(Announcement)
    user = models.ForeignKey(User)


class CommentAnnouncement(models.Model):
    subject = models.CharField(max_length=128, blank=False)
    comment = models.TextField(blank=False)
    rating = models.IntegerField(validators=[MinValueValidator(0),
                                 MaxValueValidator(10)])
    user = models.ForeignKey(User)
    announcement = models.ForeignKey(Announcement)


class StopAnnouncement(models.Model):
    stop = models.CharField(max_length=256, blank=False)
    sequence = models.IntegerField(validators=[MinValueValidator(0)])
    announcement = models.ForeignKey(Announcement)

sharingcars/routes/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext as _
from django.db import models
from common.models import APPLY_STATUS
from django.core.validators import MinValueValidator, MaxValueValidator
from common.models import User


class Route(models.Model):
    KINDS = (
        ('offer', _('Oferta')),
        ('demand', _('Demanda')),
    )
    origin = models.CharField(max_length=256, blank=False)
    destination = models.CharField(max_length=256, blank=False)
    visibility = models.BooleanField(default=False)
    description = models.TextField(blank=False)
    kind = models.CharField(max_length=64, choices=KINDS, blank=False)
    seating = models.IntegerField(validators=[MinValueValidator(0)],
                                  blank=False)
    unitPrice = models.DecimalField(max_digits=5, decimal_places=2,
                                    validators=[MinValueValidator(0)],
                                    blank=False)
    creationMoment = models.DateTimeField(auto_now=False, auto_now_add=True)
    user = models.ForeignKey(User)

    def get_rating(self):
        rating = 0
        if self.commentroute_set.all():
            rating = round(self.commentroute_set.all().aggregate(models.Sum('rating')).get('rating__sum', 0)/float(self.commentroute_set.all().count()), 1)
        return rating

    def check_applies(self):
        if self.seating == self.applyroute_set.filter(state='approach').count():
            self.applyroute_set.filter(state='waiting').update(state='rejected')

    def get_seats_free(self):
        return self.seating - self.applyroute_set.filter(state='approach').count()


class ApplyRoute(models.Model):
    creationDate = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=False)
    state = models.CharField(max_length=64, choices=APPLY_STATUS, default="waiting")

    route = models.ForeignKey(Route)
    user = models.ForeignKey(User)


class CommentRoute(models.Model):
    subject = models.CharField(max_length=128, blank=False)
    comment = models.TextField(blank=False, max_length=395)
    rating = models.IntegerField(validators=[MinValueValidator(0),
                                 MaxValueValidator(10)])
    user = models.ForeignKey(User)
    route = models.ForeignKey(Route)


class Day(models.Model):
    day = models.IntegerField()
    departTime = models.CharField(max_length=64)
    returnTime = models.CharField(max_length=64)
    active = models.BooleanField()
    route = models.ForeignKey(Route)

    class Meta:
        ordering = ['day']


class StopRoute(models.Model):
    stop = models.CharField(max_length=256, blank=False)
    sequence = models.IntegerField(validators=[MinValueValidator(0)])
    route = models.ForeignKey(Route)

sharingcars/common/views.py
# -*- coding: utf-8 -*-
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import authenticate, login
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.detail import DetailView
from django.http import Http404
from django.utils.translation import ugettext as _
from django.views.generic.edit import UpdateView
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from common.models import User, Message, Folder, Comment
from common.forms import UserRegisterForm, UserBaseForm, MessageForm, CommentCreateForm
from routes.models import CommentRoute
from announcements.models import CommentAnnouncement



class UserCreateView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'common/registration/register.html'
    success_url = reverse_lazy('index')
    success_message = u"Te has registrado correctamente en la aplicación"

    def get_success_url(self):
        form = self.get_form()
        new_user = authenticate(username=form.data['username'], password=form.data['password'])
        login(self.request, new_user)
        return self.success_url.format()


class UserProfileView(DetailView):
    model = User
    template_name = 'common/user/profile.html'
    context_object_name = 'custom_user'

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        try:
            obj = User.objects.get(user_account__username=username)
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': User._meta.verbose_name})
        return obj

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['comments_routes'] = CommentRoute.objects.filter(route__user__user_account__username=self.kwargs.get('username', ''))
        context['comments_announcements'] = CommentAnnouncement.objects.filter(announcement__user__user_account__username=self.kwargs.get('username', ''))
        return context


class UserUpdateView(SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserBaseForm
    template_name = 'common/registration/register.html'
    success_url = reverse_lazy('index')
    success_message = u"Has actualizado los datos de tu perfil correctamente"
    context_object_name = 'custom_user'

    def get_success_url(self):
        return self.success_url.format()

    def get_object(self, queryset=None):
        username = self.kwargs.get('username')
        try:
            obj = User.objects.get(user_account__username=username)
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': User._meta.verbose_name})
        return obj


class MessageCreateView(SuccessMessageMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'common/message/create.html'
    success_url = reverse_lazy('index')

    def get_success_url(self):
        return self.success_url.format()

    def get_initial(self):
        initial = super(MessageCreateView, self).get_initial()
        initial['user'] = self.request.user
        return initial

    def form_valid(self, form):
        instance = form.save(commit=False)
        sender = User.objects.get(user_account__id=self.request.user.id)
        folder = sender.folder_set.get(name="Bandeja de salida")
        instance.sender = sender
        instance.folder = folder
        return super(MessageCreateView, self).form_valid(form)

    def get_success_message(self, cleaned_data):
        return 'Su mensaje a "%s" se ha enviado correctamente' % cleaned_data.get('recipient').user_account.username


class FolderDetailsView(DetailView):
    model = Message
    template_name = 'common/message/show.html'

    def get_object(self, queryset=None):
        type = self.kwargs.get('type')
        try:
            user = User.objects.get(user_account__pk=self.request.user.id)
            if type == 'income':
                obj = user.folder_set.get(name='Bandeja de entrada')
            elif type == 'outcome':
                obj = user.folder_set.get(name='Bandeja de salida')
            elif type == 'draft':
                obj = user.folder_set.get(name='Papelera')
            else:
                raise Http404(_("No se ha encontrado la bandeja de mensajes que busca"))
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': User._meta.verbose_name})
        return obj

    def get_context_data(self, **kwargs):
        context = super(FolderDetailsView, self).get_context_data(**kwargs)
        context['type'] = self.kwargs.get('type')
        return context


class MessageDetailsView(FolderDetailsView):

    def get_context_data(self, **kwargs):
        context = super(MessageDetailsView, self).get_context_data(**kwargs)
        message = self.object.message_set.get(pk=self.kwargs.get('pk', 0))
        message.open = True
        message.save()
        context['message_see'] = message
        return context


def ajax_delete_message(request, pk):
    result = Message.objects.filter(pk=pk)
    if request.is_ajax() and result:
        message = result[0]
        user = User.objects.get(user_account__pk=request.user.pk)
        message.folder =user.folder_set.get(name='Papelera')
        message.save()
        return HttpResponse(reverse_lazy('messages-see', kwargs={'type': 'draft', 'pk': pk}))
    else:
        return HttpResponse('Error')


def ajax_hide_message(request, pk, type):
    result = Message.objects.filter(pk=pk)
    if request.is_ajax() and result:
        message = result[0]
        message.open = False
        message.save()
        return HttpResponse(reverse_lazy('messages-details', kwargs={'type': type }))
    else:
        return HttpResponse('Error')


class ReplyMessageView(MessageCreateView):

    def get_initial(self):
        initial = super(ReplyMessageView, self).get_initial()
        initial['user'] = self.request.user
        initial['sender_id'] = Message.objects.get(pk=self.kwargs.get('pk', 0)).sender.pk
        return initial


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'common/comments/create.html'
    form_class = CommentCreateForm

    def get_success_url(self):
        return reverse('user-profile', kwargs={'username': self.kwargs['username']})

    def form_valid(self, form):
        instance = form.save(commit=False)
        referrer = User.objects.get(user_account__id=self.request.user.id)
        evaluated = User.objects.get(user_account__username=self.kwargs['username'])
        instance.referrer = referrer
        instance.evaluated = evaluated
        return super(CommentCreateView, self).form_valid(form)

sharingcars/templates/common/user/profile.html
{% extends 'common/master-page/master-page.html' %}
{% block title %} SharingCars {% endblock %}
{% block contents %}{% load staticfiles %}
<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2 class="text-center">Perfil de usuario de {{ custom_user.user_account.username }}
                {% if user == custom_user.user_account %}
                    <a href="{% url 'user-update' custom_user.user_account.username %}"><i class="fa fa-pencil"></i></a>
                {% endif %}
                </h2>
                <div class="col-lg-12">
                    <div class="col-lg-3">
                        {% if custom_user.photo == 'default' %}
                            <img class="img-circle img-responsive center-block image-route-list"
                                 src="{% static 'user/image/default.jpg' %}" alt="">
                        {% else %}
                            <img class="img-circle img-responsive center-block image-route-list" src="{% static custom_user.photo %}"
                                  alt="">
                        {% endif %}
                    </div>
                    <div class="col-lg-9 margin-top-60">
                        <div class="col-lg-4 padding-0">
                            <h3>{{ custom_user.name }} {{ custom_user.surnames }}</h3>
                            <h3>{{ custom_user.calculate_age }} a&ntilde;os</h3>
                        </div>
                        <div class="col-lg-8 padding-0">
                            <h3>N&uacute;mero de rutas: <span class="font-weight-300">{{ custom_user.route_set.all|length }}</span></h3>
                            <h3>N&uacute;mero de anuncios: <span class="font-weight-300">{{ custom_user.announcement_set.all|length }}</span></h3>
                            <h3>Valoraci&oacute;n: <span class="font-weight-300">{{ custom_user.get_rating }}/10</span>
                                de <span class="font-weight-300">{{custom_user.get_num_assessments}}</span>
                                comentario{{ custom_user.get_num_assessments|pluralize:",s" }}</h3>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 user-biography">
                    <h4>Hablando de mi...</h4>
                    <div class="col-lg-12">
                        <p class="text-justify">
                            {{ custom_user.biography }}
                        </p>
                    </div>
                </div>
                <div class="col-lg-12 margin-top-20 padding-0">
                    <h2 class="text-center ">Comentarios y valoraciones</h2>
                </div>
                <div class="col-md-12 padding-0">

                <div class="tabs-section">

                  <!-- Nav Tabs -->
                  <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab-1" data-toggle="tab" aria-expanded="true"><i class="fa fa-user"></i> Comentarios</a></li>
                    <li class=""><a href="#tab-2" data-toggle="tab" aria-expanded="false"><i class="fa fa-road"></i> Comentarios a las rutas</a></li>
                    <li class=""><a href="#tab-3" data-toggle="tab" aria-expanded="false"><i class="fa fa-bullhorn"></i>Comentarios a los anuncios</a></li>
                  </ul>

                  <!-- Tab panels -->
                  <div class="tab-content padding-0">
                    <!-- Tab Content 1 -->
                    <div class="tab-pane fade active in" id="tab-1">
                      {% if custom_user.evaluated.all|length != 0%}
                        {% for comment in custom_user.evaluated.all %}
                            <div class="col-lg-12 padding-bottom-15 {% if forloop.counter|divisibleby:2 %}background-ccc{% else %}background-ddd{% endif %}">
                                <a href="{% url 'user-profile' comment.referrer.user_account.username %}">
                                    <div class="col-lg-4">
                                        <div class="col-lg-4 padding-0">
                                            {% if comment.referrer.photo == 'default' %}
                                                <img class="img-circle img-responsive image-comment-list margin-top-25-100"
                                                     src="{% static 'user/image/default.jpg' %}" alt="">
                                            {% else %}
                                                <img class="img-circle img-responsive image-comment-list margin-top-25-100" src="{% static comment.referrer.photo %}"
                                                      alt="">
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-8">
                                            <h6 class="text-center margin-top-40-100">
                                                {{ comment.referrer.user_account.username }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                                <div class="col-lg-8 comment">
                                    <h4 class="text-center">{{ comment.subject }} | {{ comment.rating }}/10</h4>
                                    <p class="text-justify">
                                        {{ comment.comment }}
                                    </p>
                                </div>

                            </div>
                        {% endfor %}
                        {% else %}
                        <div class="col-lg-12">
                            <h3 class="text-center">No hay comentarios realizados al usuario</h3>
                        </div>
                      {% endif %}
                    </div>
                    <!-- Tab Content 2 -->
                    <div class="tab-pane fade" id="tab-2">
                      {% if comments_routes|length != 0%}
                        {% for comment in comments_routes %}
                            <div class="col-lg-12 padding-bottom-15 {% if forloop.counter|divisibleby:2 %}background-ccc{% else %}background-ddd{% endif %}">
                                <a href="{% url 'user-profile' comment.user.user_account.username %}">
                                    <div class="col-lg-4">
                                        <div class="col-lg-4 padding-0">
                                            {% if comment.user.photo == 'default' %}
                                                <img class="img-circle img-responsive image-comment-list margin-top-25-100"
                                                     src="{% static 'user/image/default.jpg' %}" alt="">
                                            {% else %}
                                                <img class="img-circle img-responsive image-comment-list margin-top-25-100" src="{% static comment.user.photo %}"
                                                      alt="">
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-8">
                                            <h6 class="text-center margin-top-40-100">
                                                {{ comment.user.user_account.username }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                                <div class="col-lg-8 comment">
                                    <h4 class="text-center">{{ comment.subject }} | {{ comment.rating }}/10</h4>
                                    <p class="text-justify">
                                        {{ comment.comment }}
                                    </p>
                                </div>

                            </div>
                        {% endfor %}
                        {% else %}
                        <div class="col-lg-12">
                            <h3 class="text-center">No hay comentarios realizados a ninguna ruta del usuario</h3>
                        </div>
                      {% endif %}
                    </div>
                    <!-- Tab Content 3 -->
                    <div class="tab-pane fade" id="tab-3">
                      {% if comments_announcements|length != 0%}
                        {% for comment in comments_announcements %}
                            <div class="col-lg-12 padding-bottom-15 {% if forloop.counter|divisibleby:2 %}background-ccc{% else %}background-ddd{% endif %}">
                                <a href="{% url 'user-profile' comment.user.user_account.username %}">
                                    <div class="col-lg-4">
                                        <div class="col-lg-4 padding-0">
                                            {% if comment.user.photo == 'default' %}
                                                <img class="img-circle img-responsive image-comment-list margin-top-25-100"
                                                     src="{% static 'user/image/default.jpg' %}" alt="">
                                            {% else %}
                                                <img class="img-circle img-responsive image-comment-list margin-top-25-100" src="{% static comment.user.photo %}"
                                                      alt="">
                                            {% endif %}
                                        </div>
                                        <div class="col-lg-8">
                                            <h6 class="text-center margin-top-40-100">
                                                {{ comment.user.user_account.username }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                                <div class="col-lg-8 comment">
                                    <h4 class="text-center">{{ comment.subject }} | {{ comment.rating }}/10</h4>
                                    <p class="text-justify">
                                        {{ comment.comment }}
                                    </p>
                                </div>

                            </div>
                        {% endfor %}
                        {% else %}
                        <div class="col-lg-12">
                            <h3 class="text-center">No hay comentarios realizados a ning&uacute;n anuncio del usuario</h3>
                        </div>
                      {% endif %}

                    </div>
                  </div>

                  <!-- End Tab Panels -->

                </div>
                    {% if user != custom_user.user_account %}
                        <div class="col-lg-12 text-center margin-top-20">
                            <a href="{% url 'comment-create' custom_user.user_account.username %}" class="btn btn-system btn-large">Escribir comentario</a>
                        </div>
                    {% endif %}
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}}