sharingcars/common/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from common.views import (UserCreateView, UserProfileView, UserUpdateView, MessageCreateView, MessageDetailsView,
                          FolderDetailsView, ajax_delete_message, ajax_hide_message, ReplyMessageView,
                          CommentCreateView)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='common/index.html'),
        name='index'),
    url(r'^login/?$', 'django.contrib.auth.views.login',
        {'template_name': 'common/registration/login.html'}, name="login"),
    url(r'^logout/?$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name="logout"),
    url(r'^user/register$', UserCreateView.as_view(), name='create-user'),
    url(r'^user/update/(?P<username>.*)/$', UserUpdateView.as_view(), name='user-update'),
    url(r'^user/(?P<username>.*)/$', UserProfileView.as_view(), name='user-profile'),
    url(r'^messages/send/$', MessageCreateView.as_view(), name='messages-send'),
    url(r'^messages/delete/(?P<pk>[-\d]+)$', ajax_delete_message, name='messages-delete'),
    url(r'^messages/reply/(?P<pk>[-\d]+)$', ReplyMessageView.as_view(), name='messages-reply'),
    url(r'^messages/hide/(?P<pk>[-\d]+)/(?P<type>[-\w]+)$', ajax_hide_message, name='messages-mark-not-see'),
    url(r'^messages/(?P<type>[-\w]+)/$', FolderDetailsView.as_view(), name='messages-details'),
    url(r'^messages/(?P<type>[-\w]+)/(?P<pk>[-\w]+)$', MessageDetailsView.as_view(), name='messages-see'),
    url(r'^comment/(?P<username>.*)/$', CommentCreateView.as_view(), name='comment-create'),


]

sharingcars/routes/urls.py
from django.conf.urls import url
from routes.views import (RouteCreateView, RouteUserListView,
                          RouteUserRecommendationsListView, RouteApplyCreate,
                          RouteDetailsView, resolve_apply, RouteListView, RouteEditView,
                          StopRouteCreateView, StopRouteUpdateView, ApplyRouteReceivedUser, ApplyRoutePerformedUser,
                          RouteApplyDelete, CommentRouteCreateView)


urlpatterns = [
    url(r'^create$', RouteCreateView.as_view(), name='create-route'),
    url(r'^all$', RouteListView.as_view(), name='all-routes'),
    url(r'^user$', RouteUserListView.as_view(), name='user-routes'),
    url(r'^recommendations$', RouteUserRecommendationsListView.as_view(), name='recommendations-routes'),
    url(r'^details/(?P<pk>[-\w]+)$', RouteDetailsView.as_view(),
        name='details-route'),
    url(r'^apply/received$', ApplyRouteReceivedUser.as_view(), name='apply-route-user-received'),
    url(r'^apply/performed$', ApplyRoutePerformedUser.as_view(), name='apply-route-user-performed'),
    url(r'^apply/remove/(?P<pk>[-\w]+)$', RouteApplyDelete.as_view(), name='remove-apply-route'),
    url(r'^apply/(?P<pk>[-\w]+)$', RouteApplyCreate.as_view(), name='create-apply-route'),
    url(r'^apply/resolve/(?P<pk>[-\w]+)/(?P<action>[-\w]+)$', resolve_apply, name='resolve-apply-route'),
    url(r'^edit/(?P<pk>[-\w]+)$', RouteEditView.as_view(),
        name='edit-route'),
    url(r'^stop/create/(?P<pk>[-\w]+)$', StopRouteCreateView.as_view(),
            name='stop-route-create'),
    url(r'^stop/edit/(?P<pk>[-\w]+)$', StopRouteUpdateView.as_view(),
            name='stop-route-edit'),
    url(r'^comment/create/(?P<route_pk>[-\w]+)$', CommentRouteCreateView.as_view(), name='create-comment-route'),
]

sharingcars/sharingcars/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('common.urls')),
    url(r'^announcements/', include('announcements.urls')),
    url(r'^routes/', include('routes.urls')),
]

sharingcars/routes/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext as _
from django.db import models
from common.models import APPLY_STATUS
from django.core.validators import MinValueValidator, MaxValueValidator
from common.models import User


class Route(models.Model):
    KINDS = (
        ('offer', _('Oferta')),
        ('demand', _('Demanda')),
    )
    origin = models.CharField(max_length=256, blank=False)
    destination = models.CharField(max_length=256, blank=False)
    visibility = models.BooleanField(default=False)
    description = models.TextField(blank=False)
    kind = models.CharField(max_length=64, choices=KINDS, blank=False)
    seating = models.IntegerField(validators=[MinValueValidator(0)],
                                  blank=False)
    unitPrice = models.DecimalField(max_digits=5, decimal_places=2,
                                    validators=[MinValueValidator(0)],
                                    blank=False)
    creationMoment = models.DateTimeField(auto_now=False, auto_now_add=True)
    user = models.ForeignKey(User)

    def get_rating(self):
        rating = 0
        if self.commentroute_set.all():
            rating = round(self.commentroute_set.all().aggregate(models.Sum('rating')).get('rating__sum', 0)/float(self.commentroute_set.all().count()), 1)
        return rating

    def check_applies(self):
        if self.seating == self.applyroute_set.filter(state='approach').count():
            self.applyroute_set.filter(state='waiting').update(state='rejected')

    def get_seats_free(self):
        return self.seating - self.applyroute_set.filter(state='approach').count()


class ApplyRoute(models.Model):
    creationDate = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=False)
    state = models.CharField(max_length=64, choices=APPLY_STATUS, default="waiting")

    route = models.ForeignKey(Route)
    user = models.ForeignKey(User)


class CommentRoute(models.Model):
    subject = models.CharField(max_length=128, blank=False)
    comment = models.TextField(blank=False, max_length=395)
    rating = models.IntegerField(validators=[MinValueValidator(0),
                                 MaxValueValidator(10)])
    user = models.ForeignKey(User)
    route = models.ForeignKey(Route)


class Day(models.Model):
    day = models.IntegerField()
    departTime = models.CharField(max_length=64)
    returnTime = models.CharField(max_length=64)
    active = models.BooleanField()
    route = models.ForeignKey(Route)

    class Meta:
        ordering = ['day']


class StopRoute(models.Model):
    stop = models.CharField(max_length=256, blank=False)
    sequence = models.IntegerField(validators=[MinValueValidator(0)])
    route = models.ForeignKey(Route)

sharingcars/routes/admin.py
from django.contrib import admin
from routes.models import Route, CommentRoute, StopRoute, ApplyRoute


class RouteAdmin(admin.ModelAdmin):
    list_display = ('origin', 'destination', 'kind', 'user')


class CommentRouteAdmin(admin.ModelAdmin):
    list_display = ('user', 'route', 'rating', 'comment')


class StopRouteAdmin(admin.ModelAdmin):
    pass


class ApplyRouteAdmin(admin.ModelAdmin):
    pass


admin.site.register(ApplyRoute, ApplyRouteAdmin)
admin.site.register(StopRoute, StopRouteAdmin)
admin.site.register(Route, RouteAdmin)
admin.site.register(CommentRoute, CommentRouteAdmin)

sharingcars/routes/apps.py
from __future__ import unicode_literals

from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'routes'

sharingcars/routes/views.py
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.views.generic import DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from routes.models import Route, ApplyRoute, StopRoute, CommentRoute
from common.models import User
from routes.forms import RouteCreateForm, ApplyRouteCreateForm, RouteEditForm, StopRouteForm, CommentRouteCreateForm



class RouteCreateView(CreateView):
    model = Route
    form_class = RouteCreateForm
    template_name = 'routes/create.html'
    success_url = reverse_lazy('index')

    def get_success_url(self):
        return self.success_url.format()

    def form_valid(self, form):
        instance = form.save(commit=False)
        user = User.objects.get(user_account__id=self.request.user.id)
        instance.user = user
        return super(RouteCreateView, self).form_valid(form)


class RouteEditView(UpdateView):
    model = Route
    form_class = RouteEditForm
    template_name = 'routes/create.html'
    success_url = reverse_lazy('index')

    def get_success_url(self):
        return self.success_url.format()

    def get_initial(self):
        initial = super(RouteEditView, self).get_initial()
        for day in self.object.day_set.all():
            if day.day == 1:
                initial['monday_departTime'] = day.departTime
                initial['monday_returnTime'] = day.returnTime
            elif day.day == 2:
                initial['tuesday_departTime'] = day.departTime
                initial['tuesday_returnTime'] = day.returnTime
            elif day.day == 3:
                initial['wednesday_departTime'] = day.departTime
                initial['wednesday_returnTime'] = day.returnTime
            elif day.day == 4:
                initial['thursday_departTime'] = day.departTime
                initial['thursday_returnTime'] = day.returnTime
            elif day.day == 5:
                initial['friday_departTime'] = day.departTime
                initial['friday_returnTime'] = day.returnTime
            elif day.day == 6:
                initial['saturday_departTime'] = day.departTime
                initial['saturday_returnTime'] = day.returnTime
            elif day.day == 7:
                initial['sunday_departTime'] = day.departTime
                initial['sunday_returnTime'] = day.returnTime
        return initial


class RouteListView(ListView):
    model = Route
    template_name = 'routes/list.html'

    def get_queryset(self):
        return Route.objects.filter(visibility=True).order_by('-creationMoment')


class RouteDetailsView(DetailView):
    template_name = 'routes/show.html'

    def get_queryset(self):
        return Route.objects.filter(Q(visibility=True) | Q(user__user_account__pk=self.request.user.pk))


class RouteUserListView(ListView):
    model = Route
    template_name = 'routes/list.html'

    def get_queryset(self):
        return Route.objects.filter(user__user_account__id=self.request.user.id)


class RouteUserRecommendationsListView(ListView):
    model = Route
    template_name = 'routes/list.html'

    def get_context_data(self):
        context = super(RouteUserRecommendationsListView, self).get_context_data()
        userId = self.request.user.id
        userRoutes = Route.objects.filter(user__user_account__id=userId)
        routes = Route.objects.filter(~Q(user__user_account__id=userId), visibility=1)
        recommendations = set()
        for userRoute in userRoutes:
            for route in routes:
                if userRoute.origin == route.origin and userRoute.destination == route.destination:
                    recommendations.add(route)
                stop_origin = route.stoproute_set.filter(stop=userRoute.origin)
                stop_destination = route.stoproute_set.filter(stop=userRoute.destination)
                if stop_origin and userRoute.destination == route.destination:
                    recommendations.add(route)
                if stop_origin and stop_destination and (stop_origin[0].sequence < stop_destination[0].sequence):
                    recommendations.add(route)
                if userRoute.origin == route.origin and stop_destination:
                    recommendations.add(route)
        context['route_list'] = recommendations
        return context


class RouteApplyCreate(LoginRequiredMixin, CreateView):
    model = ApplyRoute
    template_name = 'common/form.html'
    form_class = ApplyRouteCreateForm

    def get_success_url(self):
        return reverse('details-route', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        instance = form.save(commit=False)
        user = User.objects.get(user_account__id=self.request.user.id)
        route = Route.objects.get(pk=self.kwargs['pk'])
        instance.user = user
        instance.route = route
        return super(RouteApplyCreate, self).form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_anonymous:
            user = User.objects.get(user_account__id=self.request.user.id)
            route = Route.objects.get(pk=self.kwargs['pk'])
            if route.applyroute_set.filter(user=user).exists():
                previous_url = self.request.META.get('HTTP_REFERER', None)
                messages.add_message(self.request, messages.ERROR,
                                     'Ya tiene una solicitud para esta ruta')

                if previous_url:
                    return redirect(previous_url)
                else:
                    return redirect('all-routes')
        return super(RouteApplyCreate, self).dispatch(request, *args, **kwargs)


@login_required
def resolve_apply(request, pk, action):
    apply_route = ApplyRoute.objects.get(pk=pk)
    if action == 'approach':
        if apply_route.route.get_seats_free() > 0:
            apply_route.state = 'approach'
        else:
            previous_url = request.META.get('HTTP_REFERER', None)
            messages.add_message(request, messages.ERROR, 'No puede aceptar esta solicitud porque no hay asientos libres')
            return redirect(previous_url)
    elif action == 'reject':
        apply_route.state = 'rejected'
    apply_route.save()
    apply_route.route.check_applies()
    previous_url = request.META.get('HTTP_REFERER', None)
    if previous_url:
        return redirect(previous_url)
    else:
        return redirect('details-route', pk=apply_route.route.pk)


class StopRouteCreateView(CreateView):
    model = StopRoute
    template_name = 'routes/stop/create.html'
    success_url = reverse_lazy('index')
    form_class = StopRouteForm

    def get_success_url(self):
        return self.success_url.format()

    def form_valid(self, form):
        instance = form.save(commit=False)
        route = Route.objects.get(pk=self.kwargs['pk'])
        instance.route = route
        return super(StopRouteCreateView, self).form_valid(form)


class StopRouteUpdateView(UpdateView):
    model = StopRoute
    template_name = 'routes/stop/create.html'
    success_url = reverse_lazy('index')
    form_class = StopRouteForm

    def get_success_url(self):
        return self.success_url.format()


class ApplyRouteReceivedUser(ListView):
    model = ApplyRoute
    template_name = 'routes/apply/list.html'

    def get_queryset(self):
        return ApplyRoute.objects.filter(~Q(state='rejected'),
                                         route__user__user_account__id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(ApplyRouteReceivedUser, self).get_context_data(**kwargs)
        context['title'] = u'Solicitudes de rutas recibidas'
        context['kind_apply'] = u'Ir a la ruta'
        context['received'] = True
        return context


class ApplyRoutePerformedUser(ListView):
    model = ApplyRoute
    template_name = 'routes/apply/list.html'

    def get_queryset(self):
        return ApplyRoute.objects.filter(user__user_account__id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(ApplyRoutePerformedUser, self).get_context_data(**kwargs)
        context['title'] = u'Solicitudes de rutas realizadas'
        context['kind_apply'] = u'Ir a la ruta'
        return context


class RouteApplyDelete(DeleteView):
    model = ApplyRoute
    success_url = reverse_lazy('index')

    def get_queryset(self):
        qs = super(RouteApplyDelete, self).get_queryset()
        return qs.filter(~Q(state='approach'), user__user_account=self.request.user)


class CommentRouteCreateView(LoginRequiredMixin, CreateView):
    model = CommentRoute
    template_name = 'routes/comments/create.html'
    form_class = CommentRouteCreateForm

    def get_success_url(self):
        return reverse('details-route', kwargs={'pk': self.kwargs['route_pk']})

    def form_valid(self, form):
        instance = form.save(commit=False)
        user = User.objects.get(user_account__id=self.request.user.id)
        route = Route.objects.get(pk=self.kwargs['route_pk'])
        instance.user = user
        instance.route = route
        return super(CommentRouteCreateView, self).form_valid(form)

sharingcars/templates/routes/apply/list.html
{% extends 'common/master-page/master-page.html' %}
{% block title %} SharingCars {% endblock %}
{% block contents %}{% load staticfiles %}
<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h2 class="text-center">{{ title }}</h2>
                <br>
                <table class="table table-responsive" id="id_table_apply">
                    <thead>
                    <tr>
                        <th class="text-center">{{ kind_apply }}</th>
                        <th class="text-center">Usuario</th>
                        <th class="text-center">Origen</th>
                        <th class="text-center">Destino</th>
                        <th class="text-center">Estado</th>
                        {% if received %}
                            <th class="text-center" data-sortable="false">Aprobar</th>
                            <th class="text-center" data-sortable="false">Rechazar</th>
                        {% else %}
                            <th class="text-center" data-sortable="false">Borrar</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for apply in object_list %}
                    <tr id="apply-{{apply.pk}}">
                        <td class="text-center">
                            <a href="{% url 'details-route' apply.route.pk%}">
                                Ir a la ruta
                            </a>
                        </td>
                        <td class="text-center"><a href="{% url 'user-profile' apply.user.user_account.username %}">{{ apply.user.user_account }}</a></td>
                        <td class="text-center">{{ apply.route.origin|truncatechars:20 }}</td>
                        <td class="text-center">{{ apply.route.destination }}</td>
                        <td class="text-center">{{ apply.get_state_display }}</td>

                        <td class="text-center">
                            {% if received %}
                                    {% if apply.state != 'approach' %}
                                        <a href="{% url 'resolve-apply-route' apply.pk 'approach'%}">
                                            <i class="fa fa-check text-success"></i>
                                        </a>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if apply.state != 'rejected' %}
                                        <a href="{% url 'resolve-apply-route' apply.pk 'reject'%}">
                                            <i class="fa fa-times text-danger"></i>
                                        </a>
                                    {% endif %}
                            {% else %}
                            {% if apply.state != 'approach' %}
                                <a class="delete-apply" data-pk='{{apply.id}}' href="{% url 'remove-apply-route' apply.pk %}">
                                    <i class="fa fa-trash"></i>
                                </a>
                            {% endif %}
                        {% endif %}
                        </td>

                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('#id_table_apply').DataTable({
            "order": [[ 0, "asc" ]],
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Spanish.json"
            }
        });
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        $('.delete-apply').on('click', function (event) {
            event.preventDefault();
            var csrftoken = getCookie('csrftoken');
            apply_id = this.attributes['data-pk'].value;
            if (confirm('\u00BFEst\u00e1 seguro que desea borrar esta solicitud?')) {
                $.ajax({
                        url: this.href,
                        type:  'POST',
                        data: {csrfmiddlewaretoken: csrftoken},
                        success:  function (response) {
                            $('#apply-' + apply_id).remove()
                        }
                });
            }
        });
    });
</script>
{% endblock %}}